#!/usr/bin/env python3
"""Translate all remaining Chinese text in tarf.json to English"""

import json
import re

# Comprehensive translation mapping for all resource names
TRANSLATIONS = {
    # ===== Category 01 =====
    "CIPD｜Selection methods（结构化面试等）": "CIPD | Selection Methods (Structured Interviews)",
    "SHRM Labs｜Structured interviewing & AI（减少偏差）": "SHRM Labs | Structured Interviewing & AI (Reducing Bias)",
    "BIT｜How to run structured interviews（PDF）": "BIT | How to Run Structured Interviews (PDF)",
    "SHRM｜Recruitment and Selection: Hiring the Right Person（PDF）": "SHRM | Recruitment and Selection: Hiring the Right Person (PDF)",

    # ===== Category 02 =====
    "O*NET OnLine（职业/技能/任务）": "O*NET OnLine (Occupations/Skills/Tasks)",
    "ESCO（欧盟技能/职业分类）": "ESCO (EU Skills/Occupation Classification)",
    "SFIA（数字/技术技能框架）": "SFIA (Digital/Tech Skills Framework)",
    "NICE Framework（网络安全岗位/技能通用词典）": "NICE Framework (Cybersecurity Roles/Skills Dictionary)",
    "Lightcast Skills Taxonomy（33,000+ 技能库）": "Lightcast Skills Taxonomy (33,000+ Skills Library)",
    "BLS｜OEWS（就业与工资统计）": "BLS | OEWS (Employment & Wage Statistics)",
    "levels.fyi（科技岗位薪酬）": "levels.fyi (Tech Compensation)",
    "Glassdoor（薪酬/雇主品牌）": "Glassdoor (Salary/Employer Brand)",
    "Payscale（薪酬数据和对标）": "Payscale (Compensation Data & Benchmarking)",
    "Salary.com（薪酬管理）": "Salary.com (Compensation Management)",
    "LinkedIn Salary Insights（需订阅）": "LinkedIn Salary Insights (Subscription Required)",
    "Radford（高科技薪酬调研）": "Radford (High-Tech Compensation Survey)",
    "Mercer（全球薪酬数据）": "Mercer (Global Compensation Data)",
    "Willis Towers Watson（WTW 薪酬数据）": "Willis Towers Watson (WTW Compensation Data)",
    "Robert Half｜Salary Guide（每年发布）": "Robert Half | Salary Guide (Annual)",
    "中国人力资源和社会保障部｜工资指导线": "China MOHRSS | Wage Guidelines",

    # ===== Category 03 =====
    "Dice（技术招聘）": "Dice (Tech Recruiting)",
    "AngelList / Wellfound（创业公司）": "AngelList / Wellfound (Startups)",
    "Hired（技术人才市场）": "Hired (Tech Talent Marketplace)",
    "Triplebyte (Karat)｜技术招聘": "Triplebyte (Karat) | Tech Recruiting",
    "Turing（远程开发者）": "Turing (Remote Developers)",
    "Arc.dev（远程开发者）": "Arc.dev (Remote Developers)",
    "BOSS直聘": "BOSS Zhipin",
    "拉勾（互联网招聘）": "Lagou (Internet Recruiting)",
    "智联招聘": "Zhaopin",
    "前程无忧（51job）": "51job",
    "猎聘（中高端）": "Liepin (Mid-Senior Level)",
    "脉脉（职场社交）": "Maimai (Professional Social)",
    "牛客网（校招/技术）": "Nowcoder (Campus/Tech Recruiting)",
    "Fairygodboss（女性招聘）": "Fairygodboss (Women in Tech)",
    "PowerToFly（女性&多元化）": "PowerToFly (Women & Diversity)",
    "Hirepurpose（退伍军人招聘）": "Hirepurpose (Veteran Recruiting)",
    "AbilityLinks（残障人士）": "AbilityLinks (Disability Inclusion)",
    "Radancy（雇主品牌）": "Radancy (Employer Brand)",
    "Clinch（人才获取CRM）": "Clinch (Talent Acquisition CRM)",
    "Beamery（候选人关系管理）": "Beamery (Candidate Relationship Management)",
    "Phenom People（AI 驱动 TXM）": "Phenom People (AI-Powered TXM)",
    "Upwork（综合自由职业）": "Upwork (General Freelance)",
    "Fiverr（任务制自由职业）": "Fiverr (Task-Based Freelance)",
    "Toptal（高端自由职业者）": "Toptal (Top Freelancers)",
    "FlexJobs（远程/弹性工作）": "FlexJobs (Remote/Flexible Work)",
    "Freelancer.com（综合平台）": "Freelancer.com (General Platform)",

    # ===== Category 04 =====
    "GitHub（开发者档案）": "GitHub (Developer Profiles)",
    "Stack Overflow（开发者社区）": "Stack Overflow (Developer Community)",
    "Kaggle（数据科学竞赛/档案）": "Kaggle (Data Science Competition/Profiles)",
    "HackerRank（开发者技能验证）": "HackerRank (Developer Skills Verification)",
    "LeetCode（算法训练）": "LeetCode (Algorithm Practice)",
    "GitLab（开源项目/开发者）": "GitLab (Open Source/Developers)",
    "Bitbucket（代码托管）": "Bitbucket (Code Hosting)",
    "Dribbble（设计师作品集）": "Dribbble (Designer Portfolio)",
    "Behance（创意作品集）": "Behance (Creative Portfolio)",
    "ProductHunt（产品人社区）": "ProductHunt (Product Community)",
    "Medium（内容创作者）": "Medium (Content Creators)",
    "Google Scholar（学术档案）": "Google Scholar (Academic Profiles)",
    "ResearchGate（学术社交网络）": "ResearchGate (Academic Social Network)",
    "ORCID（学术身份标识）": "ORCID (Academic Identity)",
    "Academia.edu（学术资源分享）": "Academia.edu (Academic Resource Sharing)",
    "LinkedIn（职业社交）": "LinkedIn (Professional Social)",
    "Xing（欧洲职业社交）": "Xing (European Professional Social)",
    "脉脉（中国职业社交）": "Maimai (China Professional Social)",
    "领英中国（LinkedIn China）": "LinkedIn China",

    # ===== Category 05 =====
    "LinkedIn People X-Ray（个人页）": "LinkedIn People X-Ray (Profiles)",
    "LinkedIn Company X-Ray（公司页）": "LinkedIn Company X-Ray (Company Pages)",
    "Boolean Builder（LinkedIn）": "Boolean Builder (LinkedIn)",
    "GitHub User X-Ray（用户搜索）": "GitHub User X-Ray (User Search)",
    "GitHub Code Search（代码搜索）": "GitHub Code Search",
    "GitHub Topics（话题标签）": "GitHub Topics",
    "Twitter/X 人才搜索": "Twitter/X Talent Search",
    "Indeed Resume X-Ray（简历搜索）": "Indeed Resume X-Ray (Resume Search)",
    "Google Dorking（高级搜索）": "Google Dorking (Advanced Search)",
    "Boolean Strings Bank（Boolean 模板库）": "Boolean Strings Bank (Boolean Templates)",
    "Recruiting Brainfood（Boolean 技巧）": "Recruiting Brainfood (Boolean Tips)",
    "SourceCon（Sourcing 社区）": "SourceCon (Sourcing Community)",

    # ===== Category 06 =====
    "Greenhouse（企业级 ATS）": "Greenhouse (Enterprise ATS)",
    "Lever（中型企业 ATS）": "Lever (Mid-Market ATS)",
    "Workday Recruiting（HCM 集成）": "Workday Recruiting (HCM Integration)",
    "iCIMS（大型企业）": "iCIMS (Large Enterprise)",
    "Taleo（Oracle）": "Taleo (Oracle)",
    "SuccessFactors（SAP）": "SuccessFactors (SAP)",
    "SmartRecruiters（AI 驱动）": "SmartRecruiters (AI-Powered)",
    "Jobvite（中小型企业）": "Jobvite (SMB)",
    "JazzHR（中小企业友好）": "JazzHR (SMB-Friendly)",
    "BambooHR（HR+招聘一体化）": "BambooHR (HR+Recruiting Integration)",
    "Breezy HR（可视化流程）": "Breezy HR (Visual Workflow)",
    "Recruitee（协作招聘）": "Recruitee (Collaborative Recruiting)",
    "Workable（全球中小企业）": "Workable (Global SMB)",
    "Zoho Recruit（Zoho 生态）": "Zoho Recruit (Zoho Ecosystem)",
    "北森（Beisen，中国领先）": "Beisen (China Leader)",
    "Moka（中国 SaaS ATS）": "Moka (China SaaS ATS)",
    "谷露（中国猎头 ATS）": "Gulu (China Headhunter ATS)",
    "仁云（中国 HR 一体化）": "Renyun (China HR Integration)",
    "OpenCATS（PHP 开源 ATS）": "OpenCATS (PHP Open Source ATS)",
    "JEADS（Java 开源 ATS）": "JEADS (Java Open Source ATS)",
    "Odoo Recruitment（ERP 模块）": "Odoo Recruitment (ERP Module)",
    "SeekOut（AI 人才搜索）": "SeekOut (AI Talent Search)",
    "Eightfold（AI 人才智能）": "Eightfold (AI Talent Intelligence)",
    "hireEZ（AI 外呼）": "hireEZ (AI Outbound)",
    "Entelo（多元化招聘 AI）": "Entelo (Diversity Recruiting AI)",
    "Hiretual（现 hireEZ）": "Hiretual (now hireEZ)",
    "Calendly（日程安排）": "Calendly (Scheduling)",
    "GoodTime（AI 面试排程）": "GoodTime (AI Interview Scheduling)",
    "ModernLoop（面试协调）": "ModernLoop (Interview Coordination)",
    "Cronofy（日历 API）": "Cronofy (Calendar API)",

    # ===== Category 07 =====
    "HackerRank（技术面试）": "HackerRank (Technical Interviews)",
    "Codility（代码测试）": "Codility (Code Testing)",
    "LeetCode（算法面试）": "LeetCode (Algorithm Interviews)",
    "CoderPad（协作编程）": "CoderPad (Collaborative Coding)",
    "CodeSignal（技能评估）": "CodeSignal (Skills Assessment)",
    "Karat（技术面试外包）": "Karat (Technical Interview Outsourcing)",
    "TestGorilla（多维测评）": "TestGorilla (Multi-Dimensional Assessment)",
    "Criteria Corp（认知/人格测评）": "Criteria Corp (Cognitive/Personality Assessment)",
    "SHL（心理测评）": "SHL (Psychometric Assessment)",
    "Hogan Assessments（领导力测评）": "Hogan Assessments (Leadership Assessment)",
    "Thomas International（行为分析）": "Thomas International (Behavioral Analysis)",
    "Plum.io（人才评估）": "Plum.io (Talent Assessment)",
    "Pymetrics（神经科学游戏）": "Pymetrics (Neuroscience Games)",
    "Arctic Shores（游戏化评估）": "Arctic Shores (Gamified Assessment)",
    "Vervoe（AI 技能测评）": "Vervoe (AI Skills Assessment)",
    "Harver（批量招聘评估）": "Harver (Volume Hiring Assessment)",
    "HireVue（AI 视频面试）": "HireVue (AI Video Interview)",
    "Spark Hire（视频面试）": "Spark Hire (Video Interview)",
    "VidCruiter（视频招聘）": "VidCruiter (Video Recruiting)",
    "myInterview（异步视频）": "myInterview (Async Video)",
    "Interviewing.io（匿名面试）": "Interviewing.io (Anonymous Interviews)",
    "Pramp（模拟面试）": "Pramp (Mock Interviews)",
    "Exponent（PM/设计面试）": "Exponent (PM/Design Interviews)",

    # ===== Category 08 =====
    "Checkr（美国背调）": "Checkr (US Background Check)",
    "Sterling（全球背调）": "Sterling (Global Background Check)",
    "HireRight（全球背调）": "HireRight (Global Background Check)",
    "GoodHire（中小企业背调）": "GoodHire (SMB Background Check)",
    "Certn（AI 背调）": "Certn (AI Background Check)",
    "全景求是（中国背调）": "Panorama (China Background Check)",
    "FCRA（公平信用报告法）": "FCRA (Fair Credit Reporting Act)",
    "EEOC｜Background Check Guidelines": "EEOC | Background Check Guidelines",
    "FTC｜Using Consumer Reports": "FTC | Using Consumer Reports",
    "DocuSign（电子签名）": "DocuSign (E-Signature)",
    "PandaDoc（文档自动化）": "PandaDoc (Document Automation)",
    "Deel（全球 Offer 管理）": "Deel (Global Offer Management)",
    "BambooHR（入职模块）": "BambooHR (Onboarding Module)",
    "WorkBright（远程入职）": "WorkBright (Remote Onboarding)",
    "Sapling（入职流程）": "Sapling (Onboarding Workflow)",
    "Enboarder（入职体验）": "Enboarder (Onboarding Experience)",
    "Click Boarding（入职自动化）": "Click Boarding (Onboarding Automation)",

    # ===== Category 09 =====
    "Textio（JD 优化）": "Textio (JD Optimization)",
    "Gender Decoder（性别偏差检测）": "Gender Decoder (Gender Bias Detection)",
    "Ongig（JD 分析）": "Ongig (JD Analysis)",
    "Datapeople（JD 数据驱动）": "Datapeople (Data-Driven JD)",
    "TapRecruit（智能 JD 编辑）": "TapRecruit (Smart JD Editor)",
    "SeekOut（AI 人才搜索）": "SeekOut (AI Talent Search)",
    "Eightfold（人才智能平台）": "Eightfold (Talent Intelligence Platform)",
    "hireEZ（AI 外呼招聘）": "hireEZ (AI Outbound Recruiting)",
    "Fetcher（AI 外呼）": "Fetcher (AI Outbound)",
    "Humanly（AI 候选人沟通）": "Humanly (AI Candidate Communication)",
    "Paradox/Olivia（招聘聊天机器人）": "Paradox/Olivia (Recruiting Chatbot)",
    "AllyO（AI 招聘助手）": "AllyO (AI Recruiting Assistant)",
    "XOR（招聘自动化）": "XOR (Recruiting Automation)",
    "Mya（对话式 AI）": "Mya (Conversational AI)",
    "Affinda（简历解析 API）": "Affinda (Resume Parsing API)",
    "Sovren（简历解析）": "Sovren (Resume Parsing)",
    "Textkernel（简历解析+匹配）": "Textkernel (Resume Parsing+Matching)",
    "HireVue（AI 面试分析）": "HireVue (AI Interview Analysis)",
    "Modern Hire（AI 测评）": "Modern Hire (AI Assessment)",
    "Knockri（AI 视频评估）": "Knockri (AI Video Assessment)",
    "Visier（People Analytics）": "Visier (People Analytics)",
    "One Model（HR 分析）": "One Model (HR Analytics)",
    "Eightfold Analytics（人才分析）": "Eightfold Analytics (Talent Analytics)",

    # ===== Category 10 =====
    "NIST AI RMF（AI 风险管理框架）": "NIST AI RMF (AI Risk Management Framework)",
    "ISO/IEC 42001（AI 管理体系）": "ISO/IEC 42001 (AI Management System)",
    "ISO/IEC 23894（AI 风险管理）": "ISO/IEC 23894 (AI Risk Management)",
    "IEEE 7000（伦理设计）": "IEEE 7000 (Ethical Design)",
    "OECD AI Principles（AI 原则）": "OECD AI Principles",
    "NYC Local Law 144（自动化招聘工具）": "NYC Local Law 144 (Automated Employment Decision Tools)",
    "Illinois BIPA（生物识别）": "Illinois BIPA (Biometric Information)",
    "California AB 2930（算法歧视）": "California AB 2930 (Algorithmic Discrimination)",
    "EEOC｜AI and ADA（AI 与残障法）": "EEOC | AI and ADA",
    "FTC｜AI and Fair Lending": "FTC | AI and Fair Lending",
    "EU AI Act（高风险 AI 分类）": "EU AI Act (High-Risk AI Classification)",
    "GDPR（数据保护影响评估）": "GDPR (Data Protection Impact Assessment)",
    "EU DSA（数字服务法）": "EU DSA (Digital Services Act)",
    "Holistic AI（AI 审计）": "Holistic AI (AI Audit)",
    "BABL AI（偏差审计）": "BABL AI (Bias Audit)",
    "Parity AI（公平性测试）": "Parity AI (Fairness Testing)",
    "Arthur AI（AI 监控）": "Arthur AI (AI Monitoring)",
    "Model Cards（Google 模型文档）": "Model Cards (Google Model Documentation)",
    "AI Factsheets（IBM）": "AI Factsheets (IBM)",
    "Datasheets for Datasets（数据集文档）": "Datasheets for Datasets",
    "Microsoft RAI Toolkit（负责任 AI）": "Microsoft RAI Toolkit (Responsible AI)",
    "Google PAIR（人机交互）": "Google PAIR (Human-AI Interaction)",
    "AI Now Institute（AI 政策研究）": "AI Now Institute (AI Policy Research)",
    "Partnership on AI（AI 伙伴关系）": "Partnership on AI",

    # ===== Category 11 =====
    "Fairlearn（微软公平性工具）": "Fairlearn (Microsoft Fairness Toolkit)",
    "AIF360（IBM AI 公平性工具箱）": "AIF360 (IBM AI Fairness 360)",
    "Aequitas（偏差审计框架）": "Aequitas (Bias Audit Framework)",
    "ML-fairness-gym（谷歌）": "ML-fairness-gym (Google)",
    "Themis-ml（公平性约束）": "Themis-ml (Fairness Constraints)",
    "FairML（模型审计）": "FairML (Model Audit)",
    "What-If Tool（谷歌可视化）": "What-If Tool (Google Visualization)",
    "SHAP（模型可解释性）": "SHAP (Model Interpretability)",
    "LIME（局部可解释性）": "LIME (Local Interpretability)",
    "InterpretML（微软）": "InterpretML (Microsoft)",
    "Captum（PyTorch 可解释性）": "Captum (PyTorch Interpretability)",
    "ELI5（Python 可解释性）": "ELI5 (Python Interpretability)",
    "OpenCATS（开源 ATS）": "OpenCATS (Open Source ATS)",
    "ResumeParser（简历解析）": "ResumeParser (Resume Parsing)",
    "HR.js（HR 数据处理）": "HR.js (HR Data Processing)",

    # ===== Category 12 =====
    "Deel（EOR 服务）": "Deel (EOR Services)",
    "Remote.com（全球雇佣）": "Remote.com (Global Employment)",
    "Oyster HR（分布式团队）": "Oyster HR (Distributed Teams)",
    "Papaya Global（全球薪酬）": "Papaya Global (Global Payroll)",
    "Velocity Global（EOR）": "Velocity Global (EOR)",
    "Globalization Partners（EOR）": "Globalization Partners (EOR)",
    "Multiplier（亚洲 EOR）": "Multiplier (Asia EOR)",
    "Pilot.co（国际承包商）": "Pilot.co (International Contractors)",
    "Payoneer（国际支付）": "Payoneer (International Payments)",
    "Wise Business（国际转账）": "Wise Business (International Transfers)",
    "Shield GEO（全球合规）": "Shield GEO (Global Compliance)",
    "Remote.co（远程工作资源）": "Remote.co (Remote Work Resources)",
    "We Work Remotely（远程职位）": "We Work Remotely (Remote Jobs)",
    "RemoteOK（远程招聘）": "RemoteOK (Remote Recruiting)",
    "FlexJobs（弹性工作）": "FlexJobs (Flexible Work)",
    "Nomad List（数字游民）": "Nomad List (Digital Nomads)",

    # ===== Category 13 =====
    "Boon（AI 员工推荐）": "Boon (AI Employee Referral)",
    "RolePoint（推荐管理）": "RolePoint (Referral Management)",
    "Teamable（关系招聘）": "Teamable (Relationship Recruiting)",
    "ERIN（员工推荐平台）": "ERIN (Employee Referral Platform)",
    "Drafted（网络招聘）": "Drafted (Network Recruiting)",
    "Gloat（内部人才市场）": "Gloat (Internal Talent Marketplace)",
    "Fuel50（职业路径）": "Fuel50 (Career Pathing)",
    "Phenom（内部流动）": "Phenom (Internal Mobility)",
    "Eightfold（技能匹配）": "Eightfold (Skills Matching)",
    "365Talents（AI 人才流动）": "365Talents (AI Talent Mobility)",

    # ===== Category 14 =====
    "SHRM（人力资源管理协会）": "SHRM (Society for Human Resource Management)",
    "CIPD（特许人事发展协会）": "CIPD (Chartered Institute of Personnel and Development)",
    "ATD（人才发展协会）": "ATD (Association for Talent Development)",
    "AIRS（招聘专业培训）": "AIRS (Recruiting Professional Training)",
    "ERE Media（招聘媒体）": "ERE Media (Recruiting Media)",
    "SourceCon（Sourcing 社区）": "SourceCon (Sourcing Community)",
    "ACM FAccT（公平性会议）": "ACM FAccT (Fairness Conference)",
    "NeurIPS（机器学习会议）": "NeurIPS (Machine Learning Conference)",
    "AIES（AI 伦理与社会）": "AIES (AI Ethics and Society)",
    "FAT/ML（公平性与机器学习）": "FAT/ML (Fairness and Machine Learning)",
    "Hiring Success（SmartRecruiters 书籍）": "Hiring Success (SmartRecruiters Book)",
    "Work Rules!（Google HR 书籍）": "Work Rules! (Google HR Book)",
    "Who（招聘经典）": "Who (Recruiting Classic)",
    "Talent Makers（招聘书籍）": "Talent Makers (Recruiting Book)",
    "LinkedIn Learning（招聘课程）": "LinkedIn Learning (Recruiting Courses)",
    "Coursera（HR Tech 课程）": "Coursera (HR Tech Courses)",
    "Josh Bersin Academy（HR 研究）": "Josh Bersin Academy (HR Research)",
    "Aptitude Research（招聘科技研究）": "Aptitude Research (Recruiting Tech Research)",
    "Lighthouse Research（HR 研究）": "Lighthouse Research (HR Research)",
    "Mercer（人才趋势报告）": "Mercer (Talent Trends Report)",
    "Gartner（HR 技术魔力象限）": "Gartner (HR Tech Magic Quadrant)",
    "Deloitte（人力资本趋势）": "Deloitte (Human Capital Trends)",

    # ===== Category 15 =====
    "ChatGPT（OpenAI）": "ChatGPT (OpenAI)",
    "Claude（Anthropic）": "Claude (Anthropic)",
    "Bard/Gemini（Google）": "Bard/Gemini (Google)",
    "Copilot（Microsoft）": "Copilot (Microsoft)",
    "HireVue Coach（AI 面试教练）": "HireVue Coach (AI Interview Coach)",
    "Final Round AI（面试模拟）": "Final Round AI (Interview Simulation)",
    "InterviewBuddy（AI 面试练习）": "InterviewBuddy (AI Interview Practice)",
    "Pramp（真人模拟面试）": "Pramp (Live Mock Interviews)",
    "Resume.io（AI 简历生成）": "Resume.io (AI Resume Builder)",
    "Kickresume（AI 简历）": "Kickresume (AI Resume)",
    "Rezi（ATS 优化简历）": "Rezi (ATS-Optimized Resume)",
    "Enhancv（可视化简历）": "Enhancv (Visual Resume)",
    "OpenAI API（GPT 系列）": "OpenAI API (GPT Series)",
    "Anthropic API（Claude）": "Anthropic API (Claude)",
    "Google Vertex AI（PaLM/Gemini）": "Google Vertex AI (PaLM/Gemini)",
    "LangChain（LLM 应用框架）": "LangChain (LLM Application Framework)",
    "LlamaIndex（数据索引）": "LlamaIndex (Data Indexing)",
    "Hugging Face（模型库）": "Hugging Face (Model Hub)",

    # ===== Category 16 =====
    "Handshake（美国校招）": "Handshake (US Campus Recruiting)",
    "RippleMatch（校园招聘）": "RippleMatch (Campus Recruiting)",
    "Yello（校招管理）": "Yello (Campus Recruiting Management)",
    "GradLeaders（研究生招聘）": "GradLeaders (Graduate Recruiting)",
    "Symplicity（校园职业服务）": "Symplicity (Campus Career Services)",
    "实习僧（中国实习平台）": "Shixiseng (China Internship Platform)",
    "应届生求职网": "Yingjiesheng (Fresh Graduate Job Site)",
    "牛客网（校招+技术）": "Nowcoder (Campus+Tech Recruiting)",
    "大街网（校园招聘）": "Dajie (Campus Recruiting)",
    "梧桐果（校招）": "Wutongguo (Campus Recruiting)",
    "Symba（实习管理）": "Symba (Internship Management)",
    "Intern Avenue（实习追踪）": "Intern Avenue (Internship Tracking)",
    "Parker Dewey（微实习）": "Parker Dewey (Micro-Internships)",

    # ===== Category 17 =====
    "Korn Ferry（光辉国际）": "Korn Ferry",
    "Spencer Stuart（斯宾塞斯图尔特）": "Spencer Stuart",
    "Heidrick & Struggles（海德思哲）": "Heidrick & Struggles",
    "Egon Zehnder（亿康先达）": "Egon Zehnder",
    "Russell Reynolds（罗盛咨询）": "Russell Reynolds",
    "Boyden（博敦）": "Boyden",
    "Stanton Chase（史丹顿蔡斯）": "Stanton Chase",
    "Odgers Berndtson（奥德格斯）": "Odgers Berndtson",
    "科锐国际（Career International）": "Career International",
    "光辉国际（中国）": "Korn Ferry (China)",
    "Hogan（领导力评估）": "Hogan (Leadership Assessment)",
    "DDI（发展维度）": "DDI (Development Dimensions)",
    "Korn Ferry Assessment（光辉国际评估）": "Korn Ferry Assessment",
    "SHL（高管评估）": "SHL (Executive Assessment)",
    "Caliper（人才评估）": "Caliper (Talent Assessment)",
    "ExecuNet（高管社交）": "ExecuNet (Executive Network)",
    "BoardEx（董事会数据）": "BoardEx (Board Data)",
    "Equilar（高管薪酬）": "Equilar (Executive Compensation)",
    "BlueSteps（AESC 高管职业）": "BlueSteps (AESC Executive Careers)",

    # ===== Category 18 =====
    "Cielo（全球 RPO）": "Cielo (Global RPO)",
    "Korn Ferry RPO（光辉国际）": "Korn Ferry RPO",
    "PeopleScout（RPO）": "PeopleScout (RPO)",
    "Pontoon（RPO）": "Pontoon (RPO)",
    "AMS（RPO）": "AMS (RPO)",
    "Randstad Sourceright（RPO）": "Randstad Sourceright (RPO)",
    "Hudson RPO（RPO）": "Hudson RPO",
    "ManpowerGroup（人才外包）": "ManpowerGroup (Talent Outsourcing)",
    "Kelly Services（人才派遣）": "Kelly Services (Staffing)",
    "Robert Half（专业人才）": "Robert Half (Professional Staffing)",
    "Hays（全球人才）": "Hays (Global Talent)",
    "前程无忧 RPO（中国）": "51job RPO (China)",
    "科锐国际（RPO 中国）": "Career International (RPO China)",
    "RPOA（RPO 协会）": "RPOA (RPO Association)",
    "HRO Today（RPO Baker's Dozen）": "HRO Today (RPO Baker's Dozen)",
    "Everest Group（RPO 研究）": "Everest Group (RPO Research)",

    # ===== Category 19 =====
    "Colorado（科罗拉多州）": "Colorado",
    "California（加州 SB 1162）": "California (SB 1162)",
    "New York City（纽约市）": "New York City",
    "Washington State（华盛顿州）": "Washington State",
    "Connecticut（康涅狄格州）": "Connecticut",
    "Maryland（马里兰州）": "Maryland",
    "Nevada（内华达州）": "Nevada",
    "Rhode Island（罗德岛州）": "Rhode Island",
    "EU Pay Transparency Directive（欧盟薪酬透明指令）": "EU Pay Transparency Directive",
    "UK Gender Pay Gap Reporting（英国性别薪酬差距）": "UK Gender Pay Gap Reporting",
    "Australia Workplace Gender Equality（澳大利亚）": "Australia Workplace Gender Equality",
    "Canada Pay Equity（加拿大薪酬公平）": "Canada Pay Equity",
    "Syndio（薪酬公平分析）": "Syndio (Pay Equity Analytics)",
    "Trusaic（薪酬分析）": "Trusaic (Pay Analytics)",
    "PayScale Pay Equity（薪酬公平套件）": "PayScale Pay Equity Suite",
    "Compensation Advisory Partners（薪酬咨询）": "Compensation Advisory Partners",

    # ===== Category 20 =====
    "LinkedIn Talent Solutions API": "LinkedIn Talent Solutions API",
    "Indeed Publisher API": "Indeed Publisher API",
    "ZipRecruiter API": "ZipRecruiter API",
    "Glassdoor API": "Glassdoor API",
    "Monster API": "Monster API",
    "Greenhouse API（ATS 集成）": "Greenhouse API (ATS Integration)",
    "Lever API（ATS 集成）": "Lever API (ATS Integration)",
    "Workday API（HCM 集成）": "Workday API (HCM Integration)",
    "BambooHR API（HR 数据）": "BambooHR API (HR Data)",
    "Merge.dev（HR API 聚合）": "Merge.dev (HR API Aggregation)",
    "Findem（人才数据 API）": "Findem (Talent Data API)",
    "Affinda（简历解析 API）": "Affinda (Resume Parsing API)",
    "Sovren API（简历解析）": "Sovren API (Resume Parsing)",
    "Textkernel API（简历+匹配）": "Textkernel API (Resume+Matching)",
    "Lightcast API（技能数据）": "Lightcast API (Skills Data)",
    "O*NET Web Services": "O*NET Web Services",
    "Postman Collections（招聘 API）": "Postman Collections (Recruiting APIs)",
    "Swagger Hub（API 文档）": "Swagger Hub (API Documentation)",
    "RapidAPI（API 市场）": "RapidAPI (API Marketplace)",

    # ===== Category 21 =====
    "Survale（候选人体验调研）": "Survale (Candidate Experience Survey)",
    "Starred（候选人反馈）": "Starred (Candidate Feedback)",
    "Candidate.ID（候选人旅程）": "Candidate.ID (Candidate Journey)",
    "Talent Board（CandE 奖项）": "Talent Board (CandE Awards)",
    "Universum（雇主品牌咨询）": "Universum (Employer Brand Consulting)",
    "LinkedIn Talent Brand（人才品牌）": "LinkedIn Talent Brand",
    "Glassdoor Employer Center（雇主中心）": "Glassdoor Employer Center",
    "Great Place to Work（最佳雇主）": "Great Place to Work",
    "Kununu（欧洲雇主评价）": "Kununu (European Employer Reviews)",
    "看准网（中国雇主评价）": "Kanzhun (China Employer Reviews)",
    "职友集（中国雇主信息）": "Zhiyouji (China Employer Info)",
    "Rally（招聘营销内容）": "Rally (Recruitment Marketing Content)",
    "Stories Inc.（员工故事）": "Stories Inc. (Employee Stories)",
    "CareerArc（社交招聘）": "CareerArc (Social Recruiting)",

    # ===== Category 22 =====
    "Health eCareers（医疗招聘）": "Health eCareers (Healthcare Recruiting)",
    "Doximity（医生社交网络）": "Doximity (Physician Network)",
    "PracticeLink（医生招聘）": "PracticeLink (Physician Recruiting)",
    "Vivian Health（护理招聘）": "Vivian Health (Nursing Recruiting)",
    "BioSpace（生命科学）": "BioSpace (Life Sciences)",
    "eFinancialCareers（金融招聘）": "eFinancialCareers (Finance Recruiting)",
    "Efinancialcareers（投行/对冲基金）": "Efinancialcareers (IB/Hedge Funds)",
    "Lawjobs.com（法律招聘）": "Lawjobs.com (Legal Recruiting)",
    "Above the Law（法律职业）": "Above the Law (Legal Careers)",
    "BCG Attorney Search（律师招聘）": "BCG Attorney Search (Attorney Recruiting)",
    "Snagajob（小时工）": "Snagajob (Hourly Workers)",
    "Wonolo（按需用工）": "Wonolo (On-Demand Staffing)",
    "Instawork（弹性用工）": "Instawork (Flexible Staffing)",
    "Hyer（零售/餐饮）": "Hyer (Retail/Hospitality)",
    "USAJOBS（美国联邦）": "USAJOBS (US Federal)",
    "GovernmentJobs.com（政府职位）": "GovernmentJobs.com (Government Jobs)",
    "ClearanceJobs（安全许可）": "ClearanceJobs (Security Clearance)",
    "PublicServiceCareers（公共服务）": "PublicServiceCareers (Public Service)",
    "Mediabistro（媒体/营销）": "Mediabistro (Media/Marketing)",
    "Mandy.com（影视制作）": "Mandy.com (Film Production)",
    "Creativepool（创意产业）": "Creativepool (Creative Industry)",
    "Artstation Jobs（游戏/动画）": "Artstation Jobs (Games/Animation)",

    # ===== Category 23 =====
    "GDPR 招聘合规指南": "GDPR Recruiting Compliance Guide",
    "ICO（英国数据监管）": "ICO (UK Data Regulator)",
    "CNIL（法国数据监管）": "CNIL (France Data Regulator)",
    "EU Data Protection Board（欧盟数据保护委员会）": "EU Data Protection Board",
    "CCPA/CPRA（加州隐私法）": "CCPA/CPRA (California Privacy Law)",
    "VCDPA（弗吉尼亚州）": "VCDPA (Virginia)",
    "CPA（科罗拉多州）": "CPA (Colorado)",
    "CTDPA（康涅狄格州）": "CTDPA (Connecticut)",
    "UCPA（犹他州）": "UCPA (Utah)",
    "个人信息保护法（PIPL）": "Personal Information Protection Law (PIPL)",
    "数据安全法（DSL）": "Data Security Law (DSL)",
    "网络安全法": "Cybersecurity Law",
    "OneTrust（隐私管理）": "OneTrust (Privacy Management)",
    "TrustArc（隐私合规）": "TrustArc (Privacy Compliance)",
    "BigID（数据智能）": "BigID (Data Intelligence)",
    "Securiti（AI 数据治理）": "Securiti (AI Data Governance)",
    "候选人数据保留政策": "Candidate Data Retention Policy",
    "候选人同意管理": "Candidate Consent Management",
    "数据主体访问请求（DSAR）": "Data Subject Access Requests (DSAR)",
    "候选人数据删除流程": "Candidate Data Deletion Process",

    # ===== Category 24 =====
    "SAP SuccessFactors（人才盘点）": "SAP SuccessFactors (Talent Review)",
    "Workday Talent（人才管理）": "Workday Talent (Talent Management)",
    "Oracle HCM（人才云）": "Oracle HCM (Talent Cloud)",
    "Cornerstone OnDemand（人才套件）": "Cornerstone OnDemand (Talent Suite)",
    "Lattice（绩效+人才）": "Lattice (Performance+Talent)",
    "SilkRoad（继任计划）": "SilkRoad (Succession Planning)",
    "Succession Planning Module（SAP）": "Succession Planning Module (SAP)",
    "Nakisa（组织设计）": "Nakisa (Org Design)",
    "ChartHop（组织管理）": "ChartHop (Org Management)",
    "9-Box Grid Template（九宫格模板）": "9-Box Grid Template",
    "SHRM｜Succession Planning": "SHRM | Succession Planning",
    "Talent Matrix（人才矩阵）": "Talent Matrix",
    "TalentGuard（技能管理）": "TalentGuard (Skills Management)",
    "Degreed（学习+技能）": "Degreed (Learning+Skills)",
    "SkyHive（技能 AI）": "SkyHive (Skills AI)",
    "Beamery Skills（技能图谱）": "Beamery Skills (Skills Graph)",

    # ===== Category 25 =====
    "Zapier（自动化连接器）": "Zapier (Automation Connector)",
    "Make（原 Integromat）": "Make (formerly Integromat)",
    "Workato（企业自动化）": "Workato (Enterprise Automation)",
    "Tray.io（低代码自动化）": "Tray.io (Low-Code Automation)",
    "Power Automate（微软）": "Power Automate (Microsoft)",
    "Gem（候选人外呼自动化）": "Gem (Candidate Outreach Automation)",
    "Sense（招聘自动化）": "Sense (Recruiting Automation)",
    "Loxo（AI 招聘 CRM）": "Loxo (AI Recruiting CRM)",
    "Outreach.io（销售外呼）": "Outreach.io (Sales Outreach)",
    "Salesloft（销售互动）": "Salesloft (Sales Engagement)",
    "Apollo.io（数据+外呼）": "Apollo.io (Data+Outreach)",
    "Instantly.ai（冷邮件）": "Instantly.ai (Cold Email)",
    "Lemlist（邮件序列）": "Lemlist (Email Sequences)",
    "UiPath（RPA 平台）": "UiPath (RPA Platform)",
    "Automation Anywhere（RPA）": "Automation Anywhere (RPA)",
    "Blue Prism（RPA）": "Blue Prism (RPA)",
    "Microsoft Power Automate Desktop": "Microsoft Power Automate Desktop",

    # ===== Category 26 =====
    "Korn Ferry Interview Architect（面试设计）": "Korn Ferry Interview Architect",
    "SHL Interviewer Training（面试官培训）": "SHL Interviewer Training",
    "HireVue Builder（面试构建）": "HireVue Builder",
    "BrightHire（面试辅助）": "BrightHire (Interview Intelligence)",
    "Metaview（面试记录）": "Metaview (Interview Notes)",
    "AIRS（招聘认证）": "AIRS (Recruiting Certification)",
    "SHRM CP/SCP（HR 认证）": "SHRM CP/SCP (HR Certification)",
    "LinkedIn Recruiter Training": "LinkedIn Recruiter Training",
    "Social Talent（招聘培训平台）": "Social Talent (Recruiting Training Platform)",
    "Project Implicit（隐性偏见测试）": "Project Implicit (Implicit Bias Test)",
    "Unconscious Bias Training（谷歌）": "Unconscious Bias Training (Google)",
    "LeanIn｜50 Ways to Fight Bias": "LeanIn | 50 Ways to Fight Bias",
    "Netflix Inclusion Training": "Netflix Inclusion Training",
    "SHRM｜Interviewing Guide": "SHRM | Interviewing Guide",
    "Google re:Work（面试资源）": "Google re:Work (Interview Resources)",
    "Harvard Business Review（面试文章）": "Harvard Business Review (Interview Articles)",

    # ===== Category 27 =====
    "HR Tech Conference（拉斯维加斯）": "HR Tech Conference (Las Vegas)",
    "HR Technology Europe（欧洲）": "HR Technology Europe",
    "Unleash（全球 HR Tech）": "Unleash (Global HR Tech)",
    "HR Tech China（中国 HR 科技）": "HR Tech China",
    "SourceCon（Sourcing 大会）": "SourceCon (Sourcing Conference)",
    "ERE Recruiting Conference（招聘）": "ERE Recruiting Conference",
    "RecFest（英国招聘节）": "RecFest (UK Recruiting Festival)",
    "Talent Connect（LinkedIn）": "Talent Connect (LinkedIn)",
    "Talent42（技术招聘）": "Talent42 (Tech Recruiting)",
    "SHRM Diversity Conference（多元化）": "SHRM Diversity Conference",
    "Out & Equal（LGBT+ 职场）": "Out & Equal (LGBT+ Workplace)",
    "DisabilityIN Conference（残障包容）": "DisabilityIN Conference",
    "Grace Hopper（女性科技）": "Grace Hopper (Women in Tech)",
    "World AI Summit（AI 峰会）": "World AI Summit",
    "AI World Conference（AI 大会）": "AI World Conference",
    "Future of Work Summit（未来工作）": "Future of Work Summit",
    "Gartner ReimagineHR（HR 未来）": "Gartner ReimagineHR",

    # ===== Category 28 =====
    "Hire Heroes USA（退伍军人就业）": "Hire Heroes USA",
    "RecruitMilitary（军人招聘）": "RecruitMilitary",
    "Military.com（军人职业）": "Military.com (Military Careers)",
    "Hiring Our Heroes（军人招聘计划）": "Hiring Our Heroes",
    "American Corporate Partners（军人导师）": "American Corporate Partners",
    "O*NET Military Crosswalk（军民技能转换）": "O*NET Military Crosswalk",
    "SkillBridge（军转民项目）": "SkillBridge (Military Transition Program)",
    "Credentialing Opportunities（军人认证）": "Credentialing Opportunities",
    "Military Spouse Employment": "Military Spouse Employment",
    "VETS 4100（退伍军人招聘报告）": "VETS 4100 (Veteran Hiring Report)",
    "Employer Support of Guard & Reserve": "Employer Support of Guard & Reserve",
    "SHRM｜Veteran Hiring Guide": "SHRM | Veteran Hiring Guide",

    # ===== Category 29 =====
    "AbilityJobs（残障招聘）": "AbilityJobs (Disability Recruiting)",
    "DisabledPerson.com（残障求职）": "DisabledPerson.com (Disability Jobs)",
    "Getting Hired（残障就业）": "Getting Hired (Disability Employment)",
    "Bender Consulting（残障招聘）": "Bender Consulting (Disability Recruiting)",
    "Lime Connect（残障人才）": "Lime Connect (Disability Talent)",
    "ADA.gov（美国残疾人法）": "ADA.gov (Americans with Disabilities Act)",
    "OFCCP Section 503（政府承包商）": "OFCCP Section 503 (Government Contractors)",
    "JAN（Job Accommodation Network）": "JAN (Job Accommodation Network)",
    "PEAT（无障碍技术）": "PEAT (Partnership on Employment & Accessible Technology)",
    "WAVE（网页无障碍评估）": "WAVE (Web Accessibility Evaluation)",
    "axe DevTools（无障碍测试）": "axe DevTools (Accessibility Testing)",
    "SiteImprove（网站无障碍）": "SiteImprove (Website Accessibility)",
    "Texthelp（读写辅助）": "Texthelp (Literacy Support)",
    "Specialisterne（自闭症招聘）": "Specialisterne (Autism Recruiting)",
    "Autism at Work（微软）": "Autism at Work (Microsoft)",
    "Neurodiversity Hub（神经多样性）": "Neurodiversity Hub",
    "ADHD at Work（ADHD 职场）": "ADHD at Work",

    # ===== Category 30 =====
    "JobStreet（东南亚）": "JobStreet (Southeast Asia)",
    "JobsDB（香港/东南亚）": "JobsDB (Hong Kong/Southeast Asia)",
    "Naukri.com（印度）": "Naukri.com (India)",
    "Seek（澳大利亚/新西兰）": "Seek (Australia/New Zealand)",
    "CareerBuilder Japan（日本）": "CareerBuilder Japan",
    "104 人力银行（台湾）": "104 Job Bank (Taiwan)",
    "Bayt.com（中东）": "Bayt.com (Middle East)",
    "GulfTalent（海湾地区）": "GulfTalent (Gulf Region)",
    "Jobberman（尼日利亚）": "Jobberman (Nigeria)",
    "Careers24（南非）": "Careers24 (South Africa)",
    "Computrabajo（拉美）": "Computrabajo (Latin America)",
    "Bumeran（阿根廷）": "Bumeran (Argentina)",
    "InfoJobs（西班牙/拉美）": "InfoJobs (Spain/Latin America)",
    "OCC Mundial（墨西哥）": "OCC Mundial (Mexico)",
    "StepStone（德国）": "StepStone (Germany)",
    "Totaljobs（英国）": "Totaljobs (UK)",
    "Monster Europe（欧洲）": "Monster Europe",
    "Adzuna（欧洲聚合）": "Adzuna (European Aggregator)",

    # ===== Category 31 =====
    "Recruiting Future（招聘未来）": "Recruiting Future",
    "The Chad & Cheese Podcast（招聘播客）": "The Chad & Cheese Podcast",
    "Talent Cast（人才播客）": "Talent Cast",
    "HR Happy Hour（HR 播客）": "HR Happy Hour",
    "The Recruiting Brainfood Podcast": "The Recruiting Brainfood Podcast",
    "ERE（招聘媒体）": "ERE (Recruiting Media)",
    "SHRM（HR 资讯）": "SHRM (HR News)",
    "HR Dive（HR 新闻）": "HR Dive (HR News)",
    "Recruiting Daily（招聘日报）": "Recruiting Daily",
    "HR Executive（HR 高管）": "HR Executive",
    "Hung Lee's Recruiting Brainfood": "Hung Lee's Recruiting Brainfood",
    "SHRM HR Daily（每日 HR）": "SHRM HR Daily",
    "People Managing People": "People Managing People",
    "Workology（职场学）": "Workology",
    "Josh Bersin（HR 分析）": "Josh Bersin (HR Analyst)",
    "HR Bartender（HR 调酒师）": "HR Bartender",
    "Talent Acquisition Weekly": "Talent Acquisition Weekly",
    "LinkedIn Talent Solutions（YouTube）": "LinkedIn Talent Solutions (YouTube)",
    "SHRM（YouTube）": "SHRM (YouTube)",
    "Josh Bersin（YouTube）": "Josh Bersin (YouTube)",
    "Recruiting Toolbox（YouTube）": "Recruiting Toolbox (YouTube)",

    # ===== Category 32 =====
    "SHRM｜JD 模板": "SHRM | JD Templates",
    "Indeed｜JD 模板": "Indeed | JD Templates",
    "Workable｜JD 模板库": "Workable | JD Template Library",
    "Glassdoor｜JD 样例": "Glassdoor | JD Samples",
    "Ongig｜JD 最佳实践": "Ongig | JD Best Practices",
    "SHRM｜面试评分卡": "SHRM | Interview Scorecards",
    "Google re:Work｜评分卡": "Google re:Work | Scorecards",
    "Indeed｜面试指南": "Indeed | Interview Guides",
    "Greenhouse｜面试工具包": "Greenhouse | Interview Kit",
    "SHRM｜招聘指标仪表盘": "SHRM | Recruiting Metrics Dashboard",
    "Recruiting Metrics Template（Excel）": "Recruiting Metrics Template (Excel)",
    "Hiring Funnel Template（漏斗模板）": "Hiring Funnel Template",
    "Time-to-Hire Calculator（招聘周期计算）": "Time-to-Hire Calculator",
    "SHRM｜Offer Letter 模板": "SHRM | Offer Letter Templates",
    "LegalZoom｜雇佣合同": "LegalZoom | Employment Contracts",
    "Rocket Lawyer｜合同模板": "Rocket Lawyer | Contract Templates",
    "DocuSign（电子签名）": "DocuSign (E-Signature)",
    "SHRM｜入职检查清单": "SHRM | Onboarding Checklists",
    "BambooHR｜入职模板": "BambooHR | Onboarding Templates",
    "Trello｜入职看板模板": "Trello | Onboarding Board Template",
    "Monday.com｜入职工作流": "Monday.com | Onboarding Workflow",

    # ===== Category 33 =====
    "Daniel Kahneman｜Thinking, Fast and Slow": "Daniel Kahneman | Thinking, Fast and Slow",
    "Predictably Irrational（怪诞行为学）": "Predictably Irrational",
    "Nudge（助推）": "Nudge",
    "Work Rules!（工作法则）": "Work Rules!",
    "Confirmation Bias（确认偏差）": "Confirmation Bias",
    "Halo Effect（光环效应）": "Halo Effect",
    "Anchoring Bias（锚定偏差）": "Anchoring Bias",
    "Affinity Bias（亲和偏差）": "Affinity Bias",
    "Attribution Bias（归因偏差）": "Attribution Bias",
    "SHL｜人才评估科学": "SHL | Talent Assessment Science",
    "Hogan｜人格评估研究": "Hogan | Personality Assessment Research",
    "I/O Psychology（工业与组织心理学）": "I/O Psychology (Industrial-Organizational Psychology)",
    "SIOP（工业与组织心理学会）": "SIOP (Society for Industrial and Organizational Psychology)",
    "Talent Board｜CandE 研究": "Talent Board | CandE Research",
    "候选人体验最佳实践": "Candidate Experience Best Practices",
    "求职者心理学": "Job Seeker Psychology",
    "候选人决策过程": "Candidate Decision Process",

    # ===== Category 34 =====
    "EEOC（平等就业机会委员会）": "EEOC (Equal Employment Opportunity Commission)",
    "DOL（美国劳工部）": "DOL (US Department of Labor)",
    "NLRB（国家劳动关系委员会）": "NLRB (National Labor Relations Board)",
    "OFCCP（联邦合同合规办公室）": "OFCCP (Office of Federal Contract Compliance Programs)",
    "ADA（美国残疾人法）": "ADA (Americans with Disabilities Act)",
    "ILO（国际劳工组织）": "ILO (International Labour Organization)",
    "OECD Employment（经合组织就业）": "OECD Employment",
    "EU Employment Law（欧盟劳动法）": "EU Employment Law",
    "UK ACAS（英国劳动咨询）": "UK ACAS (UK Advisory, Conciliation and Arbitration Service)",
    "中国劳动法": "China Labor Law",
    "劳动合同法": "Labor Contract Law",
    "社会保险法": "Social Insurance Law",
    "中国人力资源和社会保障部": "China Ministry of Human Resources and Social Security",
    "Littler（劳动法律所）": "Littler (Employment Law Firm)",
    "Ogletree Deakins（劳动法）": "Ogletree Deakins (Employment Law)",
    "Jackson Lewis（劳动法）": "Jackson Lewis (Employment Law)",
    "SHRM｜法律合规中心": "SHRM | Legal & Compliance Center",

    # ===== Category 35 =====
    "Visier（People Analytics 平台）": "Visier (People Analytics Platform)",
    "One Model（HR 分析）": "One Model (HR Analytics)",
    "Crunchr（People Analytics）": "Crunchr (People Analytics)",
    "ChartHop（组织+分析）": "ChartHop (Org+Analytics)",
    "Orgnostic（People Analytics）": "Orgnostic (People Analytics)",
    "Tableau（BI 工具）": "Tableau (BI Tool)",
    "Power BI（微软 BI）": "Power BI (Microsoft BI)",
    "Looker（Google BI）": "Looker (Google BI)",
    "Metabase（开源 BI）": "Metabase (Open Source BI)",
    "招聘漏斗指标": "Recruiting Funnel Metrics",
    "Time-to-Fill（填补周期）": "Time-to-Fill",
    "Cost-per-Hire（人均招聘成本）": "Cost-per-Hire",
    "Quality-of-Hire（招聘质量）": "Quality-of-Hire",
    "Source-of-Hire（渠道效果）": "Source-of-Hire",
    "Offer Acceptance Rate（Offer 接受率）": "Offer Acceptance Rate",
    "People Analytics 101（入门）": "People Analytics 101 (Introduction)",
    "SHRM｜HR Metrics": "SHRM | HR Metrics",
    "Josh Bersin｜People Analytics": "Josh Bersin | People Analytics",
    "Wharton People Analytics（沃顿）": "Wharton People Analytics",

    # ===== Category 36 =====
    "Zoom（视频会议）": "Zoom (Video Conferencing)",
    "Microsoft Teams（协作+视频）": "Microsoft Teams (Collaboration+Video)",
    "Google Meet（视频会议）": "Google Meet (Video Conferencing)",
    "Cisco Webex（企业视频）": "Cisco Webex (Enterprise Video)",
    "HireVue（视频面试）": "HireVue (Video Interview)",
    "Spark Hire（视频面试）": "Spark Hire (Video Interview)",
    "Brazen（虚拟招聘会）": "Brazen (Virtual Career Fair)",
    "Hopin（虚拟活动）": "Hopin (Virtual Events)",
    "vFairs（虚拟招聘会）": "vFairs (Virtual Career Fair)",
    "Paradox｜虚拟招聘活动": "Paradox | Virtual Recruiting Events",
    "6Connex（虚拟活动平台）": "6Connex (Virtual Event Platform)",
    "Miro（协作白板）": "Miro (Collaboration Whiteboard)",
    "Figma（设计协作）": "Figma (Design Collaboration)",
    "Notion（知识管理）": "Notion (Knowledge Management)",
    "Slack（团队沟通）": "Slack (Team Communication)",
    "Enboarder（远程入职）": "Enboarder (Remote Onboarding)",
    "Click Boarding（虚拟入职）": "Click Boarding (Virtual Onboarding)",
    "Sapling（入职自动化）": "Sapling (Onboarding Automation)",
    "Talmundo（入职体验）": "Talmundo (Onboarding Experience)",

    # ===== Category 37 =====
    "Phenom（招聘营销）": "Phenom (Recruitment Marketing)",
    "SmashFly（人才 CRM）": "SmashFly (Talent CRM)",
    "Beamery（候选人关系）": "Beamery (Candidate Relationship)",
    "Clinch（人才获取）": "Clinch (Talent Acquisition)",
    "Appcast（程序化职位广告）": "Appcast (Programmatic Job Ads)",
    "Joveo（招聘广告优化）": "Joveo (Recruiting Ad Optimization)",
    "Recruitics（招聘广告分析）": "Recruitics (Recruiting Ad Analytics)",
    "PandoLogic（AI 广告优化）": "PandoLogic (AI Ad Optimization)",
    "LinkedIn Marketing（领英营销）": "LinkedIn Marketing",
    "Facebook Jobs（Meta 招聘）": "Facebook Jobs (Meta Recruiting)",
    "Twitter Ads（X 广告）": "Twitter Ads (X Advertising)",
    "Instagram Recruiting（图片营销）": "Instagram Recruiting",
    "TikTok Recruiting（短视频招聘）": "TikTok Recruiting",
    "Canva（设计工具）": "Canva (Design Tool)",
    "Adobe Creative Cloud（设计套件）": "Adobe Creative Cloud (Design Suite)",
    "Lumen5（视频创作）": "Lumen5 (Video Creation)",
    "Descript（视频编辑）": "Descript (Video Editing)",

    # ===== Category 38 =====
    "HackerRank（技术面试）": "HackerRank (Technical Interview)",
    "Codility（代码测试）": "Codility (Code Testing)",
    "CoderPad（协作编程）": "CoderPad (Collaborative Coding)",
    "CodeSignal（技能评估）": "CodeSignal (Skills Assessment)",
    "LeetCode（算法测试）": "LeetCode (Algorithm Testing)",
    "Triplebyte（技术评估）": "Triplebyte (Technical Assessment)",
    "Qualified.io（技术面试）": "Qualified.io (Technical Interview)",
    "DevSkiller（技术筛选）": "DevSkiller (Technical Screening)",
    "Pluralsight Skills（技能评估）": "Pluralsight Skills (Skills Assessment)",
    "GitHub（开发者社区）": "GitHub (Developer Community)",
    "Stack Overflow（技术问答）": "Stack Overflow (Tech Q&A)",
    "Dev.to（开发者社区）": "Dev.to (Developer Community)",
    "Hacker News（技术新闻）": "Hacker News (Tech News)",
    "技术招聘最佳实践": "Technical Recruiting Best Practices",
    "Google｜技术面试指南": "Google | Technical Interview Guide",
    "Facebook｜工程师招聘": "Facebook | Engineering Recruiting",
    "FAANG 面试准备": "FAANG Interview Prep",

    # ===== Category 39 =====
    "LinkedIn Talent Insights（人才洞察）": "LinkedIn Talent Insights",
    "Lightcast（劳动力数据）": "Lightcast (Labor Market Data)",
    "Glassdoor Economic Research（经济研究）": "Glassdoor Economic Research",
    "Bureau of Labor Statistics（劳工统计局）": "Bureau of Labor Statistics",
    "Revelio Labs（人才情报）": "Revelio Labs (Talent Intelligence)",
    "Crayon（竞争情报）": "Crayon (Competitive Intelligence)",
    "Klue（竞品分析）": "Klue (Competitor Analysis)",
    "Kompyte（竞争追踪）": "Kompyte (Competitive Tracking)",
    "LinkedIn Talent Flow（人才流动）": "LinkedIn Talent Flow",
    "Lightcast Talent Flow（人才流动数据）": "Lightcast Talent Flow",
    "LinkedIn Hiring Trends（招聘趋势）": "LinkedIn Hiring Trends",
    "Indeed Hiring Lab（招聘研究）": "Indeed Hiring Lab",
    "Glassdoor Employment Trends（就业趋势）": "Glassdoor Employment Trends",
    "Josh Bersin（HR 趋势）": "Josh Bersin (HR Trends)",

    # ===== Category 40 =====
    "Jumio（身份验证）": "Jumio (Identity Verification)",
    "Onfido（AI 身份验证）": "Onfido (AI Identity Verification)",
    "Trulioo（全球身份验证）": "Trulioo (Global Identity Verification)",
    "Veriff（视频身份验证）": "Veriff (Video Identity Verification)",
    "National Student Clearinghouse（学历验证）": "National Student Clearinghouse",
    "WES（国际学历认证）": "WES (World Education Services)",
    "学信网（中国学历验证）": "CHSI (China Higher Education Verification)",
    "Hireright（就业验证）": "Hireright (Employment Verification)",
    "The Work Number（就业记录）": "The Work Number (Employment Records)",
    "Truework（收入+就业验证）": "Truework (Income+Employment Verification)",
    "Argyle（薪资验证 API）": "Argyle (Payroll Verification API)",
    "Checkmate（简历欺诈检测）": "Checkmate (Resume Fraud Detection)",
    "Searchbug（背景调查）": "Searchbug (Background Check)",
    "HireRight Fraud Prevention": "HireRight Fraud Prevention",

    # ===== Category 41 =====
    "Upwork（自由职业平台）": "Upwork (Freelance Platform)",
    "Fiverr（任务平台）": "Fiverr (Task Platform)",
    "Freelancer.com（全球自由职业）": "Freelancer.com (Global Freelance)",
    "99designs（设计众包）": "99designs (Design Crowdsourcing)",
    "Toptal（顶尖自由职业）": "Toptal (Top Freelancers)",
    "A.Team（精英团队）": "A.Team (Elite Teams)",
    "Catalant（专家网络）": "Catalant (Expert Network)",
    "Business Talent Group（高端咨询）": "Business Talent Group (High-End Consulting)",
    "WorkMarket（零工管理）": "WorkMarket (Gig Management)",
    "Shiftboard（排班管理）": "Shiftboard (Shift Management)",
    "SAP Fieldglass（外部人才）": "SAP Fieldglass (External Talent)",
    "Beeline（VMS）": "Beeline (VMS)",
    "Wonolo（按需蓝领）": "Wonolo (On-Demand Blue Collar)",
    "Instawork（临时工）": "Instawork (Temp Workers)",
    "Bluecrew（蓝领零工）": "Bluecrew (Blue Collar Gig)",
    "Jobandtalent（灵活用工）": "Jobandtalent (Flexible Workforce)",

    # ===== Category 42 =====
    "Pymetrics（神经科学游戏）": "Pymetrics (Neuroscience Games)",
    "Arctic Shores（游戏化测评）": "Arctic Shores (Gamified Assessment)",
    "Knack（游戏化人才评估）": "Knack (Gamified Talent Assessment)",
    "Owiwi（游戏化软技能）": "Owiwi (Gamified Soft Skills)",
    "Scoutible（游戏化招聘）": "Scoutible (Gamified Recruiting)",
    "Strivr（VR 培训）": "Strivr (VR Training)",
    "PIXO VR（VR 入职）": "PIXO VR (VR Onboarding)",
    "Talespin（VR 面试）": "Talespin (VR Interview)",
    "Mursion（VR 模拟）": "Mursion (VR Simulation)",
    "HackerRank Contests（编程竞赛）": "HackerRank Contests (Coding Competitions)",
    "Kaggle Competitions（数据科学竞赛）": "Kaggle Competitions (Data Science Competitions)",
    "Topcoder（编程挑战）": "Topcoder (Coding Challenges)",
    "MLH（Major League Hacking）": "MLH (Major League Hacking)",

    # ===== Category 43 =====
    "Cost-per-Hire Calculator（人均成本计算器）": "Cost-per-Hire Calculator",
    "SHRM｜招聘成本指南": "SHRM | Recruiting Cost Guide",
    "招聘预算模板": "Recruiting Budget Template",
    "招聘 ROI 计算器": "Recruiting ROI Calculator",
    "SHRM｜ROI Framework": "SHRM | ROI Framework",
    "Quality of Hire 框架": "Quality of Hire Framework",
    "招聘 ROI 最佳实践": "Recruiting ROI Best Practices",
    "招聘预算规划指南": "Recruiting Budget Planning Guide",
    "年度招聘预算模板": "Annual Recruiting Budget Template",
    "招聘支出跟踪": "Recruiting Spend Tracking",
    "SAP Fieldglass（供应商管理）": "SAP Fieldglass (Vendor Management)",
    "Beeline（VMS 平台）": "Beeline (VMS Platform)",
    "招聘供应商评估": "Recruiting Vendor Evaluation",
    "Agency Management Best Practices": "Agency Management Best Practices",

    # ===== Category 44 =====
    "Google｜招聘实践": "Google | Recruiting Practices",
    "Netflix｜Culture Deck": "Netflix | Culture Deck",
    "Spotify｜Squad Model": "Spotify | Squad Model",
    "Meta｜Engineering Culture": "Meta | Engineering Culture",
    "Amazon｜Leadership Principles": "Amazon | Leadership Principles",
    "Apple｜招聘理念": "Apple | Recruiting Philosophy",
    "Microsoft｜招聘实践": "Microsoft | Recruiting Practices",
    "Zappos｜文化招聘": "Zappos | Culture Recruiting",
    "HubSpot｜Culture Code": "HubSpot | Culture Code",
    "Gitlab｜Handbook（远程文化）": "Gitlab | Handbook (Remote Culture)",
    "Buffer｜透明文化": "Buffer | Transparent Culture",
    "Basecamp｜工作方式": "Basecamp | Way of Working",
    "字节跳动｜招聘文化": "ByteDance | Recruiting Culture",
    "阿里巴巴｜人才理念": "Alibaba | Talent Philosophy",
    "腾讯｜招聘实践": "Tencent | Recruiting Practices",
    "华为｜人才战略": "Huawei | Talent Strategy",
    "小米｜招聘理念": "Xiaomi | Recruiting Philosophy",
    "招聘案例研究集": "Recruiting Case Study Collection",
    "Recruiting Innovation Awards": "Recruiting Innovation Awards",
    "Best Recruiting Practices（年度）": "Best Recruiting Practices (Annual)",

    # ===== Category 45 =====
    "SHRM｜招聘政策模板": "SHRM | Recruiting Policy Templates",
    "LegalZoom｜雇佣政策": "LegalZoom | Employment Policies",
    "招聘 SOP 模板": "Recruiting SOP Templates",
    "面试流程 SOP": "Interview Process SOP",
    "Notion（知识库平台）": "Notion (Knowledge Base Platform)",
    "Confluence（企业 Wiki）": "Confluence (Enterprise Wiki)",
    "Guru（知识管理）": "Guru (Knowledge Management)",
    "Tettra（团队知识库）": "Tettra (Team Knowledge Base)",
    "招聘流程 SOP 指南": "Recruiting Process SOP Guide",
    "候选人沟通 SOP": "Candidate Communication SOP",
    "入职流程 SOP": "Onboarding Process SOP",
    "招聘术语表": "Recruiting Glossary",
    "HR 术语词典": "HR Terms Dictionary",
    "招聘缩写指南": "Recruiting Abbreviations Guide",
    "SHRM｜HR Glossary": "SHRM | HR Glossary",

    # ===== Category 46 =====
    "招聘职业发展路径": "Recruiting Career Path",
    "从 Recruiter 到 HRBP": "From Recruiter to HRBP",
    "招聘管理职业路径": "Recruiting Management Career Path",
    "TA Leader 发展指南": "TA Leader Development Guide",
    "AIRS Certifications（招聘认证）": "AIRS Certifications",
    "SHRM-CP/SCP（HR 认证）": "SHRM-CP/SCP (HR Certification)",
    "LinkedIn Recruiter Certification": "LinkedIn Recruiter Certification",
    "HRCI（PHR/SPHR）": "HRCI (PHR/SPHR)",
    "Social Talent Certification": "Social Talent Certification",
    "SourceCon Community（Sourcing 社区）": "SourceCon Community",
    "ERE Community（招聘社区）": "ERE Community",
    "SHRM Connect（HR 社区）": "SHRM Connect (HR Community)",
    "LinkedIn Groups（招聘群组）": "LinkedIn Groups (Recruiting Groups)",
    "Reddit r/recruiting": "Reddit r/recruiting",
    "招聘薪酬调研": "Recruiting Salary Survey",
    "Glassdoor｜招聘薪酬": "Glassdoor | Recruiting Salaries",
    "Payscale｜HR 薪酬": "Payscale | HR Salaries",
    "Compensation Partner Data": "Compensation Partner Data",

    # ===== Category 47 =====
    "Ban the Box（前科不问）": "Ban the Box",
    "Fair Chance Hiring（公平机会招聘）": "Fair Chance Hiring",
    "Blind Hiring（盲招）": "Blind Hiring",
    "EEOC Guidelines（平等就业指南）": "EEOC Guidelines",
    "Textio（JD 偏差检测）": "Textio (JD Bias Detection)",
    "Applied（盲招平台）": "Applied (Blind Hiring Platform)",
    "GapJumpers（技能盲测）": "GapJumpers (Blind Skills Test)",
    "Blendoor（多元化分析）": "Blendoor (Diversity Analytics)",
    "AI 招聘伦理框架": "AI Recruiting Ethics Framework",
    "Responsible AI in Hiring": "Responsible AI in Hiring",
    "AI Fairness Principles": "AI Fairness Principles",
    "Human-in-the-Loop（人类监督）": "Human-in-the-Loop",
    "SHRM｜招聘道德规范": "SHRM | Recruiting Code of Ethics",
    "AIRS｜道德招聘准则": "AIRS | Ethical Recruiting Guidelines",
    "LinkedIn｜招聘行为准则": "LinkedIn | Recruiting Code of Conduct",

    # ===== Category 48 =====
    "Gloat（内部人才市场）": "Gloat (Internal Talent Marketplace)",
    "Fuel50（职业发展）": "Fuel50 (Career Development)",
    "Eightfold（内部流动）": "Eightfold (Internal Mobility)",
    "Phenom（内部招聘）": "Phenom (Internal Recruiting)",
    "365Talents（AI 流动）": "365Talents (AI Mobility)",
    "Workday Skills Cloud（技能云）": "Workday Skills Cloud",
    "Degreed（技能图谱）": "Degreed (Skills Graph)",
    "LinkedIn Skills（技能数据）": "LinkedIn Skills (Skills Data)",
    "Career Pathing Tools": "Career Pathing Tools",
    "内部招聘流程": "Internal Recruiting Process",
    "内部候选人优先政策": "Internal Candidate Priority Policy",
    "Job Posting Policy（内部优先）": "Job Posting Policy (Internal Priority)",
    "Boon（员工推荐）": "Boon (Employee Referral)",
    "RolePoint（推荐管理）": "RolePoint (Referral Management)",
    "Teamable（关系招聘）": "Teamable (Relationship Recruiting)",
    "推荐激励方案设计": "Referral Incentive Program Design",

    # ===== Category 49 =====
    "Canva（设计工具）": "Canva (Design Tool)",
    "Figma（协作设计）": "Figma (Collaborative Design)",
    "Adobe Creative Cloud（专业设计）": "Adobe Creative Cloud (Professional Design)",
    "Piktochart（信息图）": "Piktochart (Infographics)",
    "Venngage（可视化）": "Venngage (Visualization)",
    "雇主品牌视觉指南": "Employer Brand Visual Guide",
    "招聘海报模板": "Recruiting Poster Templates",
    "JD 视觉设计": "JD Visual Design",
    "Career Site 设计趋势": "Career Site Design Trends",
    "LinkedIn Banner 设计": "LinkedIn Banner Design",
    "Instagram 招聘内容": "Instagram Recruiting Content",
    "TikTok 雇主品牌": "TikTok Employer Brand",
    "招聘社交媒体策略": "Recruiting Social Media Strategy",
    "Career Site 最佳实践": "Career Site Best Practices",
    "招聘网站 UX 设计": "Recruiting Website UX Design",
    "Mobile Career Site": "Mobile Career Site",
    "ATS Career Page Integration": "ATS Career Page Integration",

    # ===== Category 50 =====
    "Beamery（CRM 领导者）": "Beamery (CRM Leader)",
    "Avature（企业 CRM）": "Avature (Enterprise CRM)",
    "Phenom CRM（人才 CRM）": "Phenom CRM (Talent CRM)",
    "SmashFly（招聘 CRM）": "SmashFly (Recruiting CRM)",
    "Clinch（人才获取 CRM）": "Clinch (Talent Acquisition CRM)",
    "Yello（校招 CRM）": "Yello (Campus CRM)",
    "人才库构建策略": "Talent Pool Building Strategy",
    "候选人培育流程": "Candidate Nurturing Process",
    "Talent Pipeline 管理": "Talent Pipeline Management",
    "Silver Medalist 管理": "Silver Medalist Management",
    "候选人邮件序列": "Candidate Email Sequences",
    "招聘 Drip Campaign": "Recruiting Drip Campaigns",
    "候选人短信营销": "Candidate SMS Marketing",
    "多渠道候选人沟通": "Multi-Channel Candidate Communication",
    "候选人旅程设计": "Candidate Journey Design",
    "候选人体验优化": "Candidate Experience Optimization",
    "候选人反馈收集": "Candidate Feedback Collection",
    "CandE（候选人体验奖）": "CandE (Candidate Experience Awards)",

    # ===== Category 51 =====
    "SAP Autism at Work（自闭症招聘）": "SAP Autism at Work",
    "Microsoft Autism Hiring Program": "Microsoft Autism Hiring Program",
    "EY Neurodiversity CoE": "EY Neurodiversity CoE",
    "JPMorgan Autism at Work": "JPMorgan Autism at Work",
    "Specialisterne（专业机构）": "Specialisterne (Specialized Agency)",
    "Auticon（自闭症 IT 咨询）": "Auticon (Autism IT Consulting)",
    "Ultranauts（神经多样性团队）": "Ultranauts (Neurodiverse Teams)",
    "SHRM｜神经多样性指南": "SHRM | Neurodiversity Guide",
    "Harvard Business Review｜神经多样性": "Harvard Business Review | Neurodiversity",
    "Neurodiversity Hub（研究中心）": "Neurodiversity Hub (Research Center)",
    "ADHD 职场适配": "ADHD Workplace Accommodations",
    "自闭症面试适配": "Autism Interview Accommodations",
    "神经多样性评估工具": "Neurodiversity Assessment Tools",
    "工作环境适配": "Workplace Environment Accommodations",

    # ===== Category 52 =====
    "Wonolo（按需蓝领）": "Wonolo (On-Demand Blue Collar)",
    "Instawork（临时工）": "Instawork (Temp Workers)",
    "Shiftsmart（排班平台）": "Shiftsmart (Shift Platform)",
    "Wonolo（仓储/物流）": "Wonolo (Warehouse/Logistics)",
    "Hyer（零售/餐饮）": "Hyer (Retail/Hospitality)",
    "Employbridge（工业人才）": "Employbridge (Industrial Talent)",
    "TrueBlue（蓝领人才）": "TrueBlue (Blue Collar Talent)",
    "Hire Dynamics（制造业）": "Hire Dynamics (Manufacturing)",
    "PeopleReady（按需蓝领）": "PeopleReady (On-Demand Blue Collar)",
    "Jobcase（蓝领社区）": "Jobcase (Blue Collar Community)",
    "WorkStep（一线员工）": "WorkStep (Frontline Workers)",
    "移动端招聘应用": "Mobile Recruiting Apps",
    "短信招聘方案": "SMS Recruiting Solutions",
    "WhatsApp 招聘": "WhatsApp Recruiting",
    "移动端候选人体验": "Mobile Candidate Experience",
    "批量招聘工具": "Volume Hiring Tools",
    "高频招聘自动化": "High-Frequency Recruiting Automation",
    "一线员工入职": "Frontline Worker Onboarding",
    "快速招聘流程": "Rapid Hiring Process",

    # ===== Category 53 =====
    "Calendly（日程安排）": "Calendly (Scheduling)",
    "GoodTime（AI 排程）": "GoodTime (AI Scheduling)",
    "ModernLoop（面试协调）": "ModernLoop (Interview Coordination)",
    "Clara（AI 助理）": "Clara (AI Assistant)",
    "x.ai（Amy AI 助理）": "x.ai (Amy AI Assistant)",
    "Gmail（邮件）": "Gmail (Email)",
    "Outlook（微软邮件）": "Outlook (Microsoft Email)",
    "Superhuman（高效邮件）": "Superhuman (Power Email)",
    "Mixmax（销售邮件）": "Mixmax (Sales Email)",
    "Loom（视频消息）": "Loom (Video Messaging)",
    "Notion（笔记+知识库）": "Notion (Notes+Knowledge Base)",
    "Evernote（笔记）": "Evernote (Notes)",
    "Roam Research（网状笔记）": "Roam Research (Networked Notes)",
    "Obsidian（本地笔记）": "Obsidian (Local Notes)",
    "Zapier（自动化）": "Zapier (Automation)",
    "Make（自动化）": "Make (Automation)",
    "IFTTT（自动化）": "IFTTT (Automation)",
    "LinkedIn Helper（LinkedIn 工具）": "LinkedIn Helper (LinkedIn Tool)",
    "Crystal（人格分析）": "Crystal (Personality Analysis)",
    "Lusha（联系人信息）": "Lusha (Contact Info)",
    "Apollo.io（数据+外呼）": "Apollo.io (Data+Outreach)",
    "Dux-Soup（LinkedIn 自动化）": "Dux-Soup (LinkedIn Automation)",

    # ===== Category 54 =====
    "HireVue（AI 视频面试）": "HireVue (AI Video Interview)",
    "Modern Hire（AI 测评）": "Modern Hire (AI Assessment)",
    "Knockri（AI 视频评估）": "Knockri (AI Video Assessment)",
    "myInterview（AI 视频）": "myInterview (AI Video)",
    "Tengai（对话式 AI）": "Tengai (Conversational AI)",
    "Paradox/Olivia（AI 助手）": "Paradox/Olivia (AI Assistant)",
    "AllyO（AI 招聘助手）": "AllyO (AI Recruiting Assistant)",
    "XOR（AI 招聘自动化）": "XOR (AI Recruiting Automation)",
    "Humanly（AI 候选人沟通）": "Humanly (AI Candidate Communication)",
    "CodeSignal（AI 编程评估）": "CodeSignal (AI Coding Assessment)",
    "HackerRank AI（AI 技术评估）": "HackerRank AI (AI Technical Assessment)",
    "Codility AI（智能代码评估）": "Codility AI (Smart Code Assessment)",
    "SHL AI（AI 心理测评）": "SHL AI (AI Psychometric)",
    "Pymetrics（神经科学 AI）": "Pymetrics (Neuroscience AI)",
    "Plum（AI 人才匹配）": "Plum (AI Talent Matching)",
    "AI 面试偏差研究": "AI Interview Bias Research",
    "AI 面试公平性研究": "AI Interview Fairness Research",
    "视频面试 AI 伦理": "Video Interview AI Ethics",
    "AI 招聘学术论文": "AI Recruiting Academic Papers",

    # ===== Category 55 =====
    "LinkedIn Talent Trends（年度报告）": "LinkedIn Talent Trends (Annual Report)",
    "SHRM State of Workplace（年度）": "SHRM State of Workplace (Annual)",
    "Glassdoor Hiring Trends（招聘趋势）": "Glassdoor Hiring Trends",
    "Indeed Hiring Lab（招聘实验室）": "Indeed Hiring Lab",
    "Josh Bersin（年度 HR 预测）": "Josh Bersin (Annual HR Predictions)",
    "Deloitte Human Capital Trends": "Deloitte Human Capital Trends",
    "McKinsey｜Future of Work": "McKinsey | Future of Work",
    "BCG｜People Strategy": "BCG | People Strategy",
    "Gartner｜HR Research": "Gartner | HR Research",
    "Mercer｜Global Talent Trends": "Mercer | Global Talent Trends",
    "Korn Ferry｜人才趋势": "Korn Ferry | Talent Trends",
    "招聘行业分析": "Recruiting Industry Analysis",
    "HR Tech 市场分析": "HR Tech Market Analysis",
    "ATS 市场报告": "ATS Market Report",
    "AI 招聘市场规模": "AI Recruiting Market Size",
    "ACM｜AI 招聘研究": "ACM | AI Recruiting Research",
    "IEEE｜HR Tech 论文": "IEEE | HR Tech Papers",
    "SIOP（工业组织心理学研究）": "SIOP (I-O Psychology Research)",
    "BLS（劳工统计数据）": "BLS (Labor Statistics Data)",
    "LinkedIn Workforce Report（劳动力报告）": "LinkedIn Workforce Report",
    "ADP Employment Report（就业报告）": "ADP Employment Report",

    # ===== Category 56 =====
    "Slack Communities（Slack 社区）": "Slack Communities",
    "Discord（技术社区）": "Discord (Tech Communities)",
    "Meetup（线下活动）": "Meetup (Offline Events)",
    "Eventbrite（活动平台）": "Eventbrite (Event Platform)",
    "Beamery Talent Graph（人才图谱）": "Beamery Talent Graph",
    "Phenom Talent CRM（人才库）": "Phenom Talent CRM (Talent Pool)",
    "Avature（人才社区）": "Avature (Talent Community)",
    "SmashFly（人才网络）": "SmashFly (Talent Network)",
    "LinkedIn Alumni（校友网络）": "LinkedIn Alumni (Alumni Network)",
    "Graduway（校友管理）": "Graduway (Alumni Management)",
    "Hivebrite（社区平台）": "Hivebrite (Community Platform)",
    "PeopleGrove（校友+导师）": "PeopleGrove (Alumni+Mentors)",
    "社区运营最佳实践": "Community Operations Best Practices",
    "人才社区活动规划": "Talent Community Event Planning",
    "候选人培育策略": "Candidate Nurturing Strategy",
    "社区内容营销": "Community Content Marketing",

    # ===== Category 57 =====
    "Lumen5（AI 视频生成）": "Lumen5 (AI Video Generation)",
    "Descript（视频编辑+转录）": "Descript (Video Editing+Transcription)",
    "Canva Video（视频设计）": "Canva Video (Video Design)",
    "InVideo（在线视频）": "InVideo (Online Video)",
    "Animoto（简易视频）": "Animoto (Simple Video)",
    "VideoMyJob（招聘视频）": "VideoMyJob (Recruiting Video)",
    "Vidyard（商业视频）": "Vidyard (Business Video)",
    "Stories Inc.（员工故事视频）": "Stories Inc. (Employee Stories Video)",
    "Wistia（视频托管+分析）": "Wistia (Video Hosting+Analytics)",
    "员工故事采集": "Employee Story Collection",
    "Day-in-the-Life Videos（日常工作视频）": "Day-in-the-Life Videos",
    "Employee Testimonials（员工推荐语）": "Employee Testimonials",
    "Meet the Team（团队介绍）": "Meet the Team",
    "Matterport（3D 空间）": "Matterport (3D Space)",
    "360° Office Tours（360度办公室）": "360° Office Tours",
    "Virtual Reality Tours（VR 参观）": "Virtual Reality Tours",
    "Video Job Descriptions（视频 JD）": "Video Job Descriptions",

    # ===== Category 58 =====
    "Lever（招聘协作）": "Lever (Recruiting Collaboration)",
    "Greenhouse（团队协作）": "Greenhouse (Team Collaboration)",
    "Slack（团队沟通）": "Slack (Team Communication)",
    "Microsoft Teams（协作平台）": "Microsoft Teams (Collaboration Platform)",
    "Notion（团队知识库）": "Notion (Team Knowledge Base)",
    "Asana（项目管理）": "Asana (Project Management)",
    "Monday.com（工作管理）": "Monday.com (Work Management)",
    "Trello（看板管理）": "Trello (Kanban Management)",
    "Jira（敏捷项目）": "Jira (Agile Projects)",
    "ClickUp（All-in-One）": "ClickUp (All-in-One)",
    "Slack（即时通讯）": "Slack (Instant Messaging)",
    "Microsoft Teams（企业通讯）": "Microsoft Teams (Enterprise Communication)",
    "Zoom（视频会议）": "Zoom (Video Conferencing)",
    "Loom（异步视频）": "Loom (Async Video)",
    "Lattice（绩效管理）": "Lattice (Performance Management)",
    "15Five（持续反馈）": "15Five (Continuous Feedback)",
    "Culture Amp（员工体验）": "Culture Amp (Employee Experience)",
    "Betterworks（OKR 管理）": "Betterworks (OKR Management)",
    "招聘运营最佳实践": "Recruiting Operations Best Practices",
    "RecOps 团队建设": "RecOps Team Building",
    "招聘流程优化": "Recruiting Process Optimization",
    "招聘运营指标": "Recruiting Operations Metrics",
}


def add_translations(node):
    """Recursively add or update name_en for nodes"""
    name = node.get("name", "")

    # Check if translation exists in our mapping
    if name in TRANSLATIONS:
        node["name_en"] = TRANSLATIONS[name]

    # Process children recursively
    if "children" in node:
        for child in node["children"]:
            add_translations(child)

    return node


def main():
    # Read tarf.json
    with open("docs/tarf.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    # Add translations
    add_translations(data)

    # Write back
    with open("docs/tarf.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print("All translations updated!")


if __name__ == "__main__":
    main()
